### ISSUE TITLE
帮忙看下为什么失败 ，代理正常。Setting in the wsgi.py password failed!

### ISSUE THREAD

**Issue by GarfieldR** [out0fmemory/GoAgent-Always-Available#44]
If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

err
2017-07-20 10:46:56,868 - oauth2client.client - INFO - Successfully retrieved access token
Authentication successful.
2017-07-20 10:46:56,880 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=True

2017-07-20 10:46:56,881 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com
/api/appversion/rollback?app_id=liu84494946-174301&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'con
tent-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-07-20 10:46:58,325 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2017-07-20 10:46:58,326 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-
length': '161', 'cache-control': 'no-cache', 'server': 'Google Frontend', 'x-cloud-trace-context': '0e090e0338368f70be01
9f83355c4c34;o=1', 'date': 'Thu, 20 Jul 2017 02:47:02 GMT', 'alt-svc': 'quic=":443"; ma=2592000; v="39,38,37,36,35"', 'c
ontent-type': 'text/plain'}
Error 404: --- begin server output ---
This application does not exist (project_id=u'liu84494946-174301'). To create an App Engine application in this project,
 run "gcloud app create" in your console.
--- end server output ---
10:46 AM Application: liu84494946-174301
10:46 AM Host: appengine.google.com
10:46 AM Rolling back the update.
2017-07-20 10:46:58,381 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'liu84494946-1
74301'}
2017-07-20 10:46:58,381 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=Fals
e
2017-07-20 10:46:58,381 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com
/api/appversion/rollback?app_id=liu84494946-174301&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'con
tent-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-07-20 10:46:59,418 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2017-07-20 10:46:59,421 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-
length': '161', 'cache-control': 'no-cache', 'server': 'Google Frontend', 'x-cloud-trace-context': '4d4ece1ccccf7d472a71
7f0aa938f69a', 'date': 'Thu, 20 Jul 2017 02:47:03 GMT', 'alt-svc': 'quic=":443"; ma=2592000; v="39,38,37,36,35"', 'conte
nt-type': 'text/plain'}
Error 404: --- begin server output ---
This application does not exist (project_id=u'liu84494946-174301'). To create an App Engine application in this project,
 run "gcloud app create" in your console.
--- end server output ---
10:46 AM Application: liu84494946-174301
10:46 AM Host: appengine.google.com
10:46 AM Rolling back the update.
2017-07-20 10:46:59,479 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'liu84494946-1
74301'}
2017-07-20 10:46:59,480 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=Fals
e
2017-07-20 10:46:59,482 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com
/api/appversion/rollback?app_id=liu84494946-174301&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'con
tent-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-07-20 10:47:00,069 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2017-07-20 10:47:00,072 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-
length': '161', 'cache-control': 'no-cache', 'server': 'Google Frontend', 'x-cloud-trace-context': '22d5e7596338cf8d9de6
168990b245cc;o=1', 'date': 'Thu, 20 Jul 2017 02:47:04 GMT', 'alt-svc': 'quic=":443"; ma=2592000; v="39,38,37,36,35"', 'c
ontent-type': 'text/plain'}
Error 404: --- begin server output ---
This application does not exist (project_id=u'liu84494946-174301'). To create an App Engine application in this project,
 run "gcloud app create" in your console.
--- end server output ---
2017-07-20 10:47:00,086 - root - INFO - =======================
2017-07-20 10:47:00,089 - root - INFO - Deploy failed appid list:
2017-07-20 10:47:00,092 - root - INFO - - liu84494946-174301
2017-07-20 10:47:00,095 - root - INFO - == END ==
2017-07-20 10:47:00,098 - root - INFO - Setting in the wsgi.py password failed!

**Comment by caofengzi** [comment]
你的appid設置密碼了吧？

**Comment by GarfieldR** [comment]
没有密码，goagent启动也有问题
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <modul
e>
ImportError: No module named linecache
Traceback (most recent call last):
  File "<install zipextimporter>", line 1, in <module>
ImportError: No module named zipextimporter
Traceback (most recent call last):
  File "python27.py", line 5, in <module>
ImportError: No module named os

**Comment by fraugzhang** [comment]
你用的Python版本是多少，我用的是2.7.13

**Comment by GarfieldR** [comment]
我用的也是2.7.13

**Comment by fraugzhang** [comment]
我的就没问题呀!!!!



1285732286@qq.com
 
发件人： GarfieldR
发送时间： 2017-07-25 09:16
收件人： out0fmemory/GoAgent-Always-Available
抄送： SaliroidZhang; Comment
主题： Re: [out0fmemory/GoAgent-Always-Available] 帮忙看下为什么失败 ，代理正常。Setting in the wsgi.py password failed! (#44)
我用的也是2.7.13
