### ISSUE TITLE
 由于目 标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by rambosir** [out0fmemory/GoAgent-Always-Available#57]
ERROR - [Sep 13 17:32:52] create_http_request "POST https://backup2333321.appspot.com/_gh/" failed:[Errno 10061] 由于目 标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\GoAgent-Always-Available-2.0.0\local\proxylib.py", line 2086, in create_http_request
  File "D:\GoAgent-Always-Available-2.0.0\local\proxylib.py", line 2065, in create_ssl_connection
error: [Errno 10061] 由于目标计算机积极拒绝，无法连接。

请问这个是我本地问题还是？

**Comment by cmhtdv** [comment]
同是这样
而且开了很久，一个goodIP也没搜索到，你们通常多久就能收到IP啊

**Comment by out0fmemory** [comment]
什么网络呀。。。这么差

**Comment by cmhtdv** [comment]
广东东莞电信，不知什么鬼，XXNET搜了一个下午，一个IP也没，单独用gscan_quic搜索了2000个，然后用gogotester测，一个都不行，然后再试这个GoAgent-Always-Available，还是没IP

**Comment by wangyu0354** [comment]
深圳联通一样 两天一共收到2个 现在一共10个 感觉随时可能挂掉啊

**Comment by rambosir** [comment]
我这里是深圳电信

**Comment by rambosir** [comment]
@out0fmemory

**Comment by mrhso** [comment]
这个月初还好，最近就变成这样了。

**Comment by KevinJe** [comment]
同样的问题，现在根本扫不出能用的IP了，挂的也太快了。

**Comment by cmhtdv** [comment]
[Errno 10061] 由于目标计算机积极拒绝，无法连接。,这是什么问题呢，就算有IP，也打不开任何网页，但是换回自己一直用的goagent就没这问题

**Comment by mrhso** [comment]
嗯……我调查了一下，应该是最近狂封 IP 了，无解……

**Comment by mrhso** [comment]
然后有条件连 IPv6 的，先不要采用这个版本，不然扫 IP 会连到 IPv4 的无效地址……
说起来有条件连 IPv6 为什么要用 GoAgent 呢？这主要是因为某些网站没有 IPv6。

**Comment by out0fmemory** [comment]
近几天我再更新一波
